const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.video,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.video.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.video.Acts.SetMuted,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.video.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetWrapping,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.video.Acts.SetVolume,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.PlainText,
		C3.Behaviors.Fade.Acts.SetFadeInTime
	];
};
self.C3_JsPropNameTable = [
	{淡入淡出: 0},
	{首页背景: 0},
	{开始游戏按钮: 0},
	{图钉: 0},
	{寝室耳机: 0},
	{寝室背景: 0},
	{闹钟: 0},
	{黑屏手机: 0},
	{手机日历: 0},
	{mdx: 0},
	{mdx2: 0},
	{任务清单标题: 0},
	{任务清单笔记本: 0},
	{任务清单耳机: 0},
	{任务清单背景: 0},
	{女: 0},
	{对话框: 0},
	{对话框2: 0},
	{对话框3: 0},
	{小组作业1: 0},
	{开始上学: 0},
	{心理健康不论性别所以你就是沃尔玛购物袋了: 0},
	{性别背景: 0},
	{男: 0},
	{社团破冰1: 0},
	{购物袋: 0},
	{选我: 0},
	{选择你的性别: 0},
	{音符: 0},
	{校门前: 0},
	{楼梯三角: 0},
	{海报栏: 0},
	{进入校园: 0},
	{进入楼梯: 0},
	{大海报: 0},
	{小海豹: 0},
	{心理活动室背景2: 0},
	{"9a底2": 0},
	{"9b底2": 0},
	{"9c底2": 0},
	{"9d底2": 0},
	{"9a2": 0},
	{"9b2": 0},
	{"9c2": 0},
	{"9d2": 0},
	{旁白xl10: 0},
	{旁白框xl9: 0},
	{旁白框底xl12: 0},
	{社长姓名框9: 0},
	{社长名字5: 0},
	{选项框底xl5: 0},
	{小书被讨厌的勇气2: 0},
	{大书2: 0},
	{心理活动室人逐渐变多2: 0},
	{旁白框底xl13: 0},
	{旁白框xl12: 0},
	{旁白xl17: 0},
	{选项框底xl6: 0},
	{"10a2": 0},
	{"10a底2": 0},
	{"10b2": 0},
	{"10b底2": 0},
	{"10c2": 0},
	{"10c底2": 0},
	{"10d2": 0},
	{"10d底2": 0},
	{社长2: 0},
	{旁白框底xl14: 0},
	{旁白框xl13: 0},
	{社长对话10: 0},
	{社长对话11: 0},
	{旁白xl18: 0},
	{选项框底xl7: 0},
	{"11a2": 0},
	{"11b2": 0},
	{"11c2": 0},
	{"11d2": 0},
	{"11a底2": 0},
	{"11b底2": 0},
	{"11c底2": 0},
	{"11d底2": 0},
	{旁白框底xl15: 0},
	{旁白框xl14: 0},
	{选项框底xl8: 0},
	{"12a2": 0},
	{"12b2": 0},
	{"12c2": 0},
	{"12d2": 0},
	{"12a底2": 0},
	{"12b底2": 0},
	{"12c底2": 0},
	{"12d底2": 0},
	{旁白xl19: 0},
	{旁白xl20: 0},
	{旁白框底xl16: 0},
	{旁白框xl15: 0},
	{社长对话12: 0},
	{社长姓名框10: 0},
	{社长名字6: 0},
	{同学1对话6: 0},
	{同学1图片2: 0},
	{同学3: 0},
	{"13a2": 0},
	{"13b2": 0},
	{"13c2": 0},
	{"13d2": 0},
	{旁白xl21: 0},
	{旁白框底xl17: 0},
	{旁白框xl16: 0},
	{社长姓名框11: 0},
	{社长名字7: 0},
	{社长对话13: 0},
	{旁白xl22: 0},
	{旁白xl23: 0},
	{万人迷2: 0},
	{万人迷姓名2: 0},
	{万人迷对话2: 0},
	{主控内心os2: 0},
	{"14a2": 0},
	{"14b2": 0},
	{"14c2": 0},
	{"14d2": 0},
	{旁白框底xl18: 0},
	{旁白框xl17: 0},
	{社长名字8: 0},
	{社长姓名框12: 0},
	{社长对话14: 0},
	{社长对话15: 0},
	{社长对话16: 0},
	{社长对话17: 0},
	{社长对话18: 0},
	{同学1对话7: 0},
	{"15a2": 0},
	{"15b2": 0},
	{"15c2": 0},
	{"15d2": 0},
	{旁白xl24: 0},
	{社长对话19: 0},
	{旁白框底xl19: 0},
	{旁白框xl18: 0},
	{同学1副本2: 0},
	{社长姓名框13: 0},
	{同学2对话5: 0},
	{同学4: 0},
	{同学2图片2: 0},
	{主控2: 0},
	{主控对话5: 0},
	{主控对话6: 0},
	{主控对话7: 0},
	{旁白xl25: 0},
	{"16a2": 0},
	{"16c2": 0},
	{"16b2": 0},
	{"16d2": 0},
	{旁白框底xl20: 0},
	{旁白框xl19: 0},
	{同学1对话8: 0},
	{同学1对话9: 0},
	{同学1对话10: 0},
	{同学2对话6: 0},
	{旁白xl26: 0},
	{"17a2": 0},
	{"17b2": 0},
	{"17c2": 0},
	{"17d2": 0},
	{社长姓名框14: 0},
	{旁白框底xl21: 0},
	{同学2对话7: 0},
	{社长姓名框15: 0},
	{旁白xl27: 0},
	{"18a2": 0},
	{"18b2": 0},
	{"18c2": 0},
	{"18d2": 0},
	{旁白框底xl22: 0},
	{旁白框xl20: 0},
	{旁白xl28: 0},
	{同学2对话8: 0},
	{社长姓名框16: 0},
	{精灵10: 0},
	{旁白xl29: 0},
	{主控对话8: 0},
	{小海报3: 0},
	{小海报4: 0},
	{海报3: 0},
	{海报4: 0},
	{旁白xl30: 0},
	{旁白xl31: 0},
	{人群2: 0},
	{新人3: 0},
	{新人4: 0},
	{新人框3: 0},
	{新人框4: 0},
	{精灵11: 0},
	{分值4: 0},
	{分值5: 0},
	{分值6: 0},
	{精灵12: 0},
	{鼠标: 0},
	{触控: 0},
	{惊吓主控: 0},
	{同学小C: 0},
	{同学小A: 0},
	{主控: 0},
	{一教楼前: 0},
	{旁白框底: 0},
	{旁白框: 0},
	{旁白1: 0},
	{"1a": 0},
	{"1b": 0},
	{"1c": 0},
	{"1a底": 0},
	{"1b底": 0},
	{"1c底": 0},
	{选项框底: 0},
	{一教楼前2: 0},
	{旁白框底2: 0},
	{旁白框2: 0},
	{同学a对话1: 0},
	{选项框底2: 0},
	{姓名框: 0},
	{同学a: 0},
	{播客: 0},
	{"1d底": 0},
	{"1d": 0},
	{链接: 0},
	{"2a": 0},
	{"2a底": 0},
	{"2d底": 0},
	{"2b": 0},
	{"2c": 0},
	{"2c底": 0},
	{"2b底": 0},
	{"2d": 0},
	{旁白2: 0},
	{链接2: 0},
	{链接3: 0},
	{旁白3: 0},
	{老师: 0},
	{选择你的座位: 0},
	{教室: 0},
	{座位选择区域: 0},
	{教室近景: 0},
	{旁白框底灰: 0},
	{旁白框底白: 0},
	{下课交作业: 0},
	{视频: 0},
	{精灵: 0},
	{老师姓名框: 0},
	{QLS: 0},
	{isClickable: 0},
	{视频2: 0},
	{自行组队: 0},
	{精灵3: 0},
	{九宫图: 0},
	{链接4: 0},
	{旁白框3: 0},
	{旁白框4: 0},
	{旁白框底3: 0},
	{文本: 0},
	{新消息: 0},
	{组队邀请: 0},
	{微信通知: 0},
	{一起来吗: 0},
	{好的好的: 0},
	{q4白底: 0},
	{q4灰底: 0},
	{q4打破沉默: 0},
	{q4答案底: 0},
	{"4a底": 0},
	{"4a": 0},
	{"4b": 0},
	{"4d": 0},
	{q3白底: 0},
	{姓名框2: 0},
	{q3灰底: 0},
	{q3找同伴: 0},
	{q3答案底: 0},
	{"3b底": 0},
	{"3b": 0},
	{"3d底": 0},
	{"3c底": 0},
	{"3a底": 0},
	{"3d": 0},
	{"3c": 0},
	{"3a": 0},
	{"4b底": 0},
	{"4c底": 0},
	{"4d底": 0},
	{"4c": 0},
	{i人灰底: 0},
	{i人白底: 0},
	{i人焦虑: 0},
	{同学C底: 0},
	{同学C: 0},
	{双击查看科普: 0},
	{q4打破沉默2: 0},
	{q4打破沉默3: 0},
	{q4白底2: 0},
	{q4灰底2: 0},
	{q5纠正别人: 0},
	{q5白底: 0},
	{q5灰底: 0},
	{"5d": 0},
	{q6答案底: 0},
	{a底: 0},
	{c底: 0},
	{d底: 0},
	{b底: 0},
	{"5c": 0},
	{"5b": 0},
	{"5a": 0},
	{科普内容: 0},
	{同学B: 0},
	{同学B底: 0},
	{蓝色: 0},
	{文本2: 0},
	{同学Bcue流程: 0},
	{点击继续: 0},
	{老师布置任务: 0},
	{老师pre底: 0},
	{老师布置pre: 0},
	{c自荐当组长: 0},
	{b提议分工: 0},
	{精灵forq5纠正: 0},
	{分工时会: 0},
	{精灵2: 0},
	{精灵4: 0},
	{精灵5: 0},
	{精灵6: 0},
	{科普精灵: 0},
	{正经科普: 0},
	{"6a": 0},
	{"6b": 0},
	{"6c": 0},
	{"6d": 0},
	{书包: 0},
	{作业: 0},
	{头像名字底: 0},
	{同学C底3: 0},
	{q5灰底2: 0},
	{旁白灰底: 0},
	{精灵7: 0},
	{找老师精灵: 0},
	{文本3: 0},
	{交作业: 0},
	{最终分工: 0},
	{教室权威q6: 0},
	{"7b": 0},
	{"7a": 0},
	{"7c": 0},
	{"7d": 0},
	{走廊: 0},
	{精灵8: 0},
	{乐手X: 0},
	{好好聊聊: 0},
	{"8a": 0},
	{"8b": 0},
	{"8c": 0},
	{"8d": 0},
	{精灵9: 0},
	{破冰: 0},
	{OS: 0},
	{边走边想: 0},
	{忽视精灵: 0},
	{"9a": 0},
	{"9b": 0},
	{"9c": 0},
	{"9d": 0},
	{分值: 0},
	{症状: 0},
	{结果评语1: 0},
	{旁白xl13: 0},
	{同学2对话4: 0},
	{同学2: 0},
	{主控对话4: 0},
	{旁白xl11: 0},
	{同学2对话3: 0},
	{旁白xl12: 0},
	{"18a": 0},
	{"18b": 0},
	{"18c": 0},
	{"18d": 0},
	{同学1对话3: 0},
	{同学1对话4: 0},
	{同学1对话5: 0},
	{同学2对话2: 0},
	{旁白xl9: 0},
	{"17a": 0},
	{"17b": 0},
	{"17c": 0},
	{"17d": 0},
	{同学1: 0},
	{同学1副本: 0},
	{同学1对话2: 0},
	{同学2对话1: 0},
	{主控对话1: 0},
	{主控对话2: 0},
	{主控对话3: 0},
	{"16a": 0},
	{"16b": 0},
	{"16c": 0},
	{"16d": 0},
	{社长名字4: 0},
	{社长对话5: 0},
	{社长对话6: 0},
	{社长对话7: 0},
	{社长对话8: 0},
	{社长对话9: 0},
	{"15a": 0},
	{"15b": 0},
	{"15c": 0},
	{"15d": 0},
	{旁白xl14: 0},
	{社长名字3: 0},
	{社长对话4: 0},
	{旁白xl7: 0},
	{万人迷姓名: 0},
	{万人迷对话1: 0},
	{主控内心os1: 0},
	{旁白xl8: 0},
	{"14a": 0},
	{"14b": 0},
	{"14c": 0},
	{"14d": 0},
	{社长对话3: 0},
	{社长名字2: 0},
	{同学1对话1: 0},
	{"13a": 0},
	{"13b": 0},
	{"13c": 0},
	{"13d": 0},
	{旁白xl6: 0},
	{"12a": 0},
	{"12b": 0},
	{"12c": 0},
	{"12d": 0},
	{旁白xl4: 0},
	{旁白xl5: 0},
	{社长名字: 0},
	{社长对话1: 0},
	{社长对话2: 0},
	{旁白xl3: 0},
	{"11a": 0},
	{"11b": 0},
	{"11c": 0},
	{"11d": 0},
	{心理活动室人逐渐变多: 0},
	{旁白xl2: 0},
	{"10a": 0},
	{"10b": 0},
	{"10c": 0},
	{"10d": 0},
	{新人2: 0},
	{新人: 0},
	{旁白xl1: 0},
	{旁白xl15: 0},
	{旁白xl16: 0},
	{旁白框底xl11: 0},
	{旁白框xl11: 0},
	{同学2图片: 0},
	{社长姓名框8: 0},
	{选项框底xl4: 0},
	{旁白框底xl10: 0},
	{旁白框xl10: 0},
	{社长姓名框7: 0},
	{"12a底": 0},
	{"12b底": 0},
	{"12c底": 0},
	{"12d底": 0},
	{旁白框底xl9: 0},
	{同学1图片: 0},
	{社长姓名框6: 0},
	{旁白框底xl8: 0},
	{旁白框xl8: 0},
	{社长姓名框5: 0},
	{旁白框底xl7: 0},
	{旁白框xl7: 0},
	{社长姓名框4: 0},
	{社长: 0},
	{旁白框底xl6: 0},
	{旁白框xl6: 0},
	{社长姓名框3: 0},
	{旁白框底xl5: 0},
	{旁白框xl5: 0},
	{社长姓名框2: 0},
	{旁白框底xl4: 0},
	{旁白框xl4: 0},
	{旁白框底xl3: 0},
	{旁白框xl3: 0},
	{社长姓名框: 0},
	{选项框底xl3: 0},
	{"11a底": 0},
	{"11b底": 0},
	{"11c底": 0},
	{"11d底": 0},
	{旁白框底xl2: 0},
	{旁白框xl2: 0},
	{选项框底xl2: 0},
	{"10a底": 0},
	{"10b底": 0},
	{"10c底": 0},
	{"10d底": 0},
	{新人框2: 0},
	{新人框: 0},
	{旁白框底xl1: 0},
	{旁白框xl1: 0},
	{选项框底xl1: 0},
	{"9a底": 0},
	{"9b底": 0},
	{"9c底": 0},
	{"9d底": 0},
	{小书被讨厌的勇气: 0},
	{大书: 0},
	{小海报1: 0},
	{小海报2: 0},
	{万人迷: 0},
	{海报2: 0},
	{心理活动室背景: 0},
	{海报1: 0},
	{人群: 0},
	{乐手: 0},
	{食堂门口: 0},
	{食堂活动: 0},
	{玩游戏吗: 0},
	{游戏文字提示: 0},
	{"19a": 0},
	{"10a4": 0},
	{"19b": 0},
	{"19c": 0},
	{"19d": 0},
	{食堂精灵: 0},
	{精灵13: 0},
	{精灵14: 0},
	{精灵15: 0},
	{结果精灵: 0},
	{报告消息: 0},
	{结果消息: 0},
	{最终数据: 0},
	{查看结果: 0},
	{精灵16: 0},
	{结果评语2: 0},
	{结果评语3: 0},
	{结果评语4: 0},
	{精灵17: 0},
	{科普内容2: 0},
	{建议1: 0},
	{建议2: 0},
	{建议3: 0},
	{建议4: 0},
	{小贴士: 0},
	{结尾: 0},
	{结束语1: 0},
	{结束语2: 0},
	{结束语3: 0},
	{精灵18: 0},
	{结束语4: 0},
	{结束语5: 0},
	{结束语6: 0},
	{结束语7: 0},
	{结束语8: 0},
	{结束语9: 0},
	{精灵19: 0},
	{精灵20: 0},
	{pic: 0},
	{朋友d: 0},
	{pic3: 0},
	{Clicked: 0}
];

self.InstanceType = {
	首页背景: class extends self.ISpriteInstance {},
	开始游戏按钮: class extends self.ISpriteInstance {},
	图钉: class extends self.ISpriteInstance {},
	寝室耳机: class extends self.ISpriteInstance {},
	寝室背景: class extends self.ISpriteInstance {},
	闹钟: class extends self.IWorldInstance {},
	黑屏手机: class extends self.ISpriteInstance {},
	手机日历: class extends self.ISpriteInstance {},
	mdx: class extends self.ITextInstance {},
	mdx2: class extends self.ITextInstance {},
	任务清单标题: class extends self.ITextInstance {},
	任务清单笔记本: class extends self.ISpriteInstance {},
	任务清单耳机: class extends self.ISpriteInstance {},
	任务清单背景: class extends self.ISpriteInstance {},
	女: class extends self.ISpriteInstance {},
	对话框: class extends self.ISpriteInstance {},
	对话框2: class extends self.ISpriteInstance {},
	对话框3: class extends self.ISpriteInstance {},
	小组作业1: class extends self.ITextInstance {},
	开始上学: class extends self.ITextInstance {},
	心理健康不论性别所以你就是沃尔玛购物袋了: class extends self.ITextInstance {},
	性别背景: class extends self.ISpriteInstance {},
	男: class extends self.ISpriteInstance {},
	社团破冰1: class extends self.ITextInstance {},
	购物袋: class extends self.ISpriteInstance {},
	选我: class extends self.ITextInstance {},
	选择你的性别: class extends self.ITextInstance {},
	音符: class extends self.ISpriteInstance {},
	校门前: class extends self.ISpriteInstance {},
	楼梯三角: class extends self.ISpriteInstance {},
	海报栏: class extends self.ISpriteInstance {},
	进入校园: class extends self.ITextInstance {},
	进入楼梯: class extends self.ITextInstance {},
	大海报: class extends self.ISpriteInstance {},
	小海豹: class extends self.ISpriteInstance {},
	心理活动室背景2: class extends self.ISpriteInstance {},
	_9a底2: class extends self.ISpriteInstance {},
	_9b底2: class extends self.ISpriteInstance {},
	_9c底2: class extends self.ISpriteInstance {},
	_9d底2: class extends self.ISpriteInstance {},
	_9a2: class extends self.ITextInstance {},
	_9b2: class extends self.ITextInstance {},
	_9c2: class extends self.ITextInstance {},
	_9d2: class extends self.ITextInstance {},
	旁白xl10: class extends self.ITextInstance {},
	旁白框xl9: class extends self.ISpriteInstance {},
	旁白框底xl12: class extends self.ISpriteInstance {},
	社长姓名框9: class extends self.ISpriteInstance {},
	社长名字5: class extends self.ITextInstance {},
	选项框底xl5: class extends self.ISpriteInstance {},
	小书被讨厌的勇气2: class extends self.ISpriteInstance {},
	大书2: class extends self.ISpriteInstance {},
	心理活动室人逐渐变多2: class extends self.IWorldInstance {},
	旁白框底xl13: class extends self.ISpriteInstance {},
	旁白框xl12: class extends self.ISpriteInstance {},
	旁白xl17: class extends self.ITextInstance {},
	选项框底xl6: class extends self.ISpriteInstance {},
	_10a2: class extends self.ITextInstance {},
	_10a底2: class extends self.ISpriteInstance {},
	_10b2: class extends self.ITextInstance {},
	_10b底2: class extends self.ISpriteInstance {},
	_10c2: class extends self.ITextInstance {},
	_10c底2: class extends self.ISpriteInstance {},
	_10d2: class extends self.ITextInstance {},
	_10d底2: class extends self.ISpriteInstance {},
	社长2: class extends self.ISpriteInstance {},
	旁白框底xl14: class extends self.ISpriteInstance {},
	旁白框xl13: class extends self.ISpriteInstance {},
	社长对话10: class extends self.ITextInstance {},
	社长对话11: class extends self.ITextInstance {},
	旁白xl18: class extends self.ITextInstance {},
	选项框底xl7: class extends self.ISpriteInstance {},
	_11a2: class extends self.ITextInstance {},
	_11b2: class extends self.ITextInstance {},
	_11c2: class extends self.ITextInstance {},
	_11d2: class extends self.ITextInstance {},
	_11a底2: class extends self.ISpriteInstance {},
	_11b底2: class extends self.ISpriteInstance {},
	_11c底2: class extends self.ISpriteInstance {},
	_11d底2: class extends self.ISpriteInstance {},
	旁白框底xl15: class extends self.ISpriteInstance {},
	旁白框xl14: class extends self.ISpriteInstance {},
	选项框底xl8: class extends self.ISpriteInstance {},
	_12a2: class extends self.ITextInstance {},
	_12b2: class extends self.ITextInstance {},
	_12c2: class extends self.ITextInstance {},
	_12d2: class extends self.ITextInstance {},
	_12a底2: class extends self.ISpriteInstance {},
	_12b底2: class extends self.ISpriteInstance {},
	_12c底2: class extends self.ISpriteInstance {},
	_12d底2: class extends self.ISpriteInstance {},
	旁白xl19: class extends self.ITextInstance {},
	旁白xl20: class extends self.ITextInstance {},
	旁白框底xl16: class extends self.ISpriteInstance {},
	旁白框xl15: class extends self.ISpriteInstance {},
	社长对话12: class extends self.ITextInstance {},
	社长姓名框10: class extends self.ISpriteInstance {},
	社长名字6: class extends self.ITextInstance {},
	同学1对话6: class extends self.ITextInstance {},
	同学1图片2: class extends self.ISpriteInstance {},
	同学3: class extends self.ITextInstance {},
	_13a2: class extends self.ITextInstance {},
	_13b2: class extends self.ITextInstance {},
	_13c2: class extends self.ITextInstance {},
	_13d2: class extends self.ITextInstance {},
	旁白xl21: class extends self.ITextInstance {},
	旁白框底xl17: class extends self.ISpriteInstance {},
	旁白框xl16: class extends self.ISpriteInstance {},
	社长姓名框11: class extends self.ISpriteInstance {},
	社长名字7: class extends self.ITextInstance {},
	社长对话13: class extends self.ITextInstance {},
	旁白xl22: class extends self.ITextInstance {},
	旁白xl23: class extends self.ITextInstance {},
	万人迷2: class extends self.ISpriteInstance {},
	万人迷姓名2: class extends self.ITextInstance {},
	万人迷对话2: class extends self.ITextInstance {},
	主控内心os2: class extends self.ITextInstance {},
	_14a2: class extends self.ITextInstance {},
	_14b2: class extends self.ITextInstance {},
	_14c2: class extends self.ITextInstance {},
	_14d2: class extends self.ITextInstance {},
	旁白框底xl18: class extends self.ISpriteInstance {},
	旁白框xl17: class extends self.ISpriteInstance {},
	社长名字8: class extends self.ITextInstance {},
	社长姓名框12: class extends self.ISpriteInstance {},
	社长对话14: class extends self.ITextInstance {},
	社长对话15: class extends self.ITextInstance {},
	社长对话16: class extends self.ITextInstance {},
	社长对话17: class extends self.ITextInstance {},
	社长对话18: class extends self.ITextInstance {},
	同学1对话7: class extends self.ITextInstance {},
	_15a2: class extends self.ITextInstance {},
	_15b2: class extends self.ITextInstance {},
	_15c2: class extends self.ITextInstance {},
	_15d2: class extends self.ITextInstance {},
	旁白xl24: class extends self.ITextInstance {},
	社长对话19: class extends self.ITextInstance {},
	旁白框底xl19: class extends self.ISpriteInstance {},
	旁白框xl18: class extends self.ISpriteInstance {},
	同学1副本2: class extends self.ITextInstance {},
	社长姓名框13: class extends self.ISpriteInstance {},
	同学2对话5: class extends self.ITextInstance {},
	同学4: class extends self.ITextInstance {},
	同学2图片2: class extends self.ISpriteInstance {},
	主控2: class extends self.ISpriteInstance {},
	主控对话5: class extends self.ITextInstance {},
	主控对话6: class extends self.ITextInstance {},
	主控对话7: class extends self.ITextInstance {},
	旁白xl25: class extends self.ITextInstance {},
	_16a2: class extends self.ITextInstance {},
	_16c2: class extends self.ITextInstance {},
	_16b2: class extends self.ITextInstance {},
	_16d2: class extends self.ITextInstance {},
	旁白框底xl20: class extends self.ISpriteInstance {},
	旁白框xl19: class extends self.ISpriteInstance {},
	同学1对话8: class extends self.ITextInstance {},
	同学1对话9: class extends self.ITextInstance {},
	同学1对话10: class extends self.ITextInstance {},
	同学2对话6: class extends self.ITextInstance {},
	旁白xl26: class extends self.ITextInstance {},
	_17a2: class extends self.ITextInstance {},
	_17b2: class extends self.ITextInstance {},
	_17c2: class extends self.ITextInstance {},
	_17d2: class extends self.ITextInstance {},
	社长姓名框14: class extends self.ISpriteInstance {},
	旁白框底xl21: class extends self.ISpriteInstance {},
	同学2对话7: class extends self.ITextInstance {},
	社长姓名框15: class extends self.ISpriteInstance {},
	旁白xl27: class extends self.ITextInstance {},
	_18a2: class extends self.ITextInstance {},
	_18b2: class extends self.ITextInstance {},
	_18c2: class extends self.ITextInstance {},
	_18d2: class extends self.ITextInstance {},
	旁白框底xl22: class extends self.ISpriteInstance {},
	旁白框xl20: class extends self.ISpriteInstance {},
	旁白xl28: class extends self.ITextInstance {},
	同学2对话8: class extends self.ITextInstance {},
	社长姓名框16: class extends self.ISpriteInstance {},
	精灵10: class extends self.ISpriteInstance {},
	旁白xl29: class extends self.ITextInstance {},
	主控对话8: class extends self.ITextInstance {},
	小海报3: class extends self.ISpriteInstance {},
	小海报4: class extends self.ISpriteInstance {},
	海报3: class extends self.ISpriteInstance {},
	海报4: class extends self.ISpriteInstance {},
	旁白xl30: class extends self.ITextInstance {},
	旁白xl31: class extends self.ITextInstance {},
	人群2: class extends self.ISpriteInstance {},
	新人3: class extends self.ITextInstance {},
	新人4: class extends self.ITextInstance {},
	新人框3: class extends self.ISpriteInstance {},
	新人框4: class extends self.ISpriteInstance {},
	精灵11: class extends self.ISpriteInstance {},
	分值4: class extends self.ITextInstance {},
	分值5: class extends self.ITextInstance {},
	分值6: class extends self.ITextInstance {},
	精灵12: class extends self.ISpriteInstance {},
	鼠标: class extends self.IInstance {},
	触控: class extends self.IInstance {},
	惊吓主控: class extends self.ISpriteInstance {},
	同学小C: class extends self.ISpriteInstance {},
	同学小A: class extends self.ISpriteInstance {},
	主控: class extends self.ISpriteInstance {},
	一教楼前: class extends self.ISpriteInstance {},
	旁白框底: class extends self.ISpriteInstance {},
	旁白框: class extends self.ISpriteInstance {},
	旁白1: class extends self.ITextInstance {},
	_1a: class extends self.ITextInstance {},
	_1b: class extends self.ITextInstance {},
	_1c: class extends self.ITextInstance {},
	_1a底: class extends self.ISpriteInstance {},
	_1b底: class extends self.ISpriteInstance {},
	_1c底: class extends self.ISpriteInstance {},
	选项框底: class extends self.ISpriteInstance {},
	一教楼前2: class extends self.ISpriteInstance {},
	旁白框底2: class extends self.ISpriteInstance {},
	旁白框2: class extends self.ISpriteInstance {},
	同学a对话1: class extends self.ITextInstance {},
	选项框底2: class extends self.ISpriteInstance {},
	姓名框: class extends self.ISpriteInstance {},
	同学a: class extends self.ITextInstance {},
	播客: class extends self.IInstance {},
	_1d底: class extends self.ISpriteInstance {},
	_1d: class extends self.ITextInstance {},
	链接: class extends self.ISpriteInstance {},
	_2a: class extends self.ITextInstance {},
	_2a底: class extends self.ISpriteInstance {},
	_2d底: class extends self.ISpriteInstance {},
	_2b: class extends self.ITextInstance {},
	_2c: class extends self.ITextInstance {},
	_2c底: class extends self.ISpriteInstance {},
	_2b底: class extends self.ISpriteInstance {},
	_2d: class extends self.ITextInstance {},
	旁白2: class extends self.ITextInstance {},
	链接2: class extends self.ISpriteInstance {},
	链接3: class extends self.ISpriteInstance {},
	旁白3: class extends self.ITextInstance {},
	老师: class extends self.ISpriteInstance {},
	选择你的座位: class extends self.ITextInstance {},
	教室: class extends self.ISpriteInstance {},
	座位选择区域: class extends self.ISpriteInstance {},
	教室近景: class extends self.ISpriteInstance {},
	旁白框底灰: class extends self.ISpriteInstance {},
	旁白框底白: class extends self.ISpriteInstance {},
	下课交作业: class extends self.ITextInstance {},
	视频: class extends self.IWorldInstance {},
	精灵: class extends self.ISpriteInstance {},
	老师姓名框: class extends self.ISpriteInstance {},
	QLS: class extends self.ITextInstance {},
	视频2: class extends self.IWorldInstance {},
	自行组队: class extends self.ITextInstance {},
	精灵3: class extends self.ISpriteInstance {},
	九宫图: class extends self.IWorldInstance {},
	链接4: class extends self.ISpriteInstance {},
	旁白框3: class extends self.ISpriteInstance {},
	旁白框4: class extends self.ISpriteInstance {},
	旁白框底3: class extends self.ISpriteInstance {},
	文本: class extends self.ITextInstance {},
	新消息: class extends self.ITextInstance {},
	组队邀请: class extends self.ISpriteInstance {},
	微信通知: class extends self.ISpriteInstance {},
	一起来吗: class extends self.ITextInstance {},
	好的好的: class extends self.ITextInstance {},
	q4白底: class extends self.ISpriteInstance {},
	q4灰底: class extends self.ISpriteInstance {},
	q4打破沉默: class extends self.ITextInstance {},
	q4答案底: class extends self.ISpriteInstance {},
	_4a底: class extends self.ISpriteInstance {},
	_4a: class extends self.ITextInstance {},
	_4b: class extends self.ITextInstance {},
	_4d: class extends self.ITextInstance {},
	q3白底: class extends self.ISpriteInstance {},
	姓名框2: class extends self.ISpriteInstance {},
	q3灰底: class extends self.ISpriteInstance {},
	q3找同伴: class extends self.ITextInstance {},
	q3答案底: class extends self.ISpriteInstance {},
	_3b底: class extends self.ISpriteInstance {},
	_3b: class extends self.ITextInstance {},
	_3d底: class extends self.ISpriteInstance {},
	_3c底: class extends self.ISpriteInstance {},
	_3a底: class extends self.ISpriteInstance {},
	_3d: class extends self.ITextInstance {},
	_3c: class extends self.ITextInstance {},
	_3a: class extends self.ITextInstance {},
	_4b底: class extends self.ISpriteInstance {},
	_4c底: class extends self.ISpriteInstance {},
	_4d底: class extends self.ISpriteInstance {},
	_4c: class extends self.ITextInstance {},
	i人灰底: class extends self.ISpriteInstance {},
	i人白底: class extends self.ISpriteInstance {},
	i人焦虑: class extends self.ITextInstance {},
	同学C底: class extends self.ISpriteInstance {},
	同学C: class extends self.ITextInstance {},
	双击查看科普: class extends self.ITextInstance {},
	q4打破沉默2: class extends self.ITextInstance {},
	q4打破沉默3: class extends self.ITextInstance {},
	q4白底2: class extends self.ISpriteInstance {},
	q4灰底2: class extends self.ISpriteInstance {},
	q5纠正别人: class extends self.ITextInstance {},
	q5白底: class extends self.ISpriteInstance {},
	q5灰底: class extends self.ISpriteInstance {},
	_5d: class extends self.ITextInstance {},
	q6答案底: class extends self.ISpriteInstance {},
	a底: class extends self.ISpriteInstance {},
	c底: class extends self.ISpriteInstance {},
	d底: class extends self.ISpriteInstance {},
	b底: class extends self.ISpriteInstance {},
	_5c: class extends self.ITextInstance {},
	_5b: class extends self.ITextInstance {},
	_5a: class extends self.ITextInstance {},
	科普内容: class extends self.ITextInstance {},
	同学B: class extends self.ITextInstance {},
	同学B底: class extends self.ISpriteInstance {},
	蓝色: class extends self.ISpriteInstance {},
	文本2: class extends self.ITextInstance {},
	同学Bcue流程: class extends self.ITextInstance {},
	点击继续: class extends self.ITextInstance {},
	老师布置任务: class extends self.ITextInstance {},
	老师pre底: class extends self.ISpriteInstance {},
	老师布置pre: class extends self.ITextInstance {},
	c自荐当组长: class extends self.ITextInstance {},
	b提议分工: class extends self.ITextInstance {},
	精灵forq5纠正: class extends self.ISpriteInstance {},
	分工时会: class extends self.ITextInstance {},
	精灵2: class extends self.ISpriteInstance {},
	精灵4: class extends self.ISpriteInstance {},
	精灵5: class extends self.ISpriteInstance {},
	精灵6: class extends self.ISpriteInstance {},
	科普精灵: class extends self.ISpriteInstance {},
	正经科普: class extends self.ISpriteInstance {},
	_6a: class extends self.ITextInstance {},
	_6b: class extends self.ITextInstance {},
	_6c: class extends self.ITextInstance {},
	_6d: class extends self.ITextInstance {},
	书包: class extends self.ISpriteInstance {},
	作业: class extends self.ISpriteInstance {},
	头像名字底: class extends self.ISpriteInstance {},
	同学C底3: class extends self.ISpriteInstance {},
	q5灰底2: class extends self.ISpriteInstance {},
	旁白灰底: class extends self.ISpriteInstance {},
	精灵7: class extends self.ISpriteInstance {},
	找老师精灵: class extends self.ISpriteInstance {},
	文本3: class extends self.ITextInstance {},
	交作业: class extends self.ITextInstance {},
	最终分工: class extends self.ITextInstance {},
	教室权威q6: class extends self.ITextInstance {},
	_7b: class extends self.ITextInstance {},
	_7a: class extends self.ITextInstance {},
	_7c: class extends self.ITextInstance {},
	_7d: class extends self.ITextInstance {},
	走廊: class extends self.ISpriteInstance {},
	精灵8: class extends self.ISpriteInstance {},
	乐手X: class extends self.ITextInstance {},
	好好聊聊: class extends self.ITextInstance {},
	_8a: class extends self.ITextInstance {},
	_8b: class extends self.ITextInstance {},
	_8c: class extends self.ITextInstance {},
	_8d: class extends self.ITextInstance {},
	精灵9: class extends self.ISpriteInstance {},
	破冰: class extends self.ITextInstance {},
	OS: class extends self.ITextInstance {},
	边走边想: class extends self.ITextInstance {},
	忽视精灵: class extends self.ISpriteInstance {},
	_9a: class extends self.ITextInstance {},
	_9b: class extends self.ITextInstance {},
	_9c: class extends self.ITextInstance {},
	_9d: class extends self.ITextInstance {},
	分值: class extends self.ITextInstance {},
	症状: class extends self.ITextInstance {},
	结果评语1: class extends self.ITextInstance {},
	旁白xl13: class extends self.ITextInstance {},
	同学2对话4: class extends self.ITextInstance {},
	同学2: class extends self.ITextInstance {},
	主控对话4: class extends self.ITextInstance {},
	旁白xl11: class extends self.ITextInstance {},
	同学2对话3: class extends self.ITextInstance {},
	旁白xl12: class extends self.ITextInstance {},
	_18a: class extends self.ITextInstance {},
	_18b: class extends self.ITextInstance {},
	_18c: class extends self.ITextInstance {},
	_18d: class extends self.ITextInstance {},
	同学1对话3: class extends self.ITextInstance {},
	同学1对话4: class extends self.ITextInstance {},
	同学1对话5: class extends self.ITextInstance {},
	同学2对话2: class extends self.ITextInstance {},
	旁白xl9: class extends self.ITextInstance {},
	_17a: class extends self.ITextInstance {},
	_17b: class extends self.ITextInstance {},
	_17c: class extends self.ITextInstance {},
	_17d: class extends self.ITextInstance {},
	同学1: class extends self.ITextInstance {},
	同学1副本: class extends self.ITextInstance {},
	同学1对话2: class extends self.ITextInstance {},
	同学2对话1: class extends self.ITextInstance {},
	主控对话1: class extends self.ITextInstance {},
	主控对话2: class extends self.ITextInstance {},
	主控对话3: class extends self.ITextInstance {},
	_16a: class extends self.ITextInstance {},
	_16b: class extends self.ITextInstance {},
	_16c: class extends self.ITextInstance {},
	_16d: class extends self.ITextInstance {},
	社长名字4: class extends self.ITextInstance {},
	社长对话5: class extends self.ITextInstance {},
	社长对话6: class extends self.ITextInstance {},
	社长对话7: class extends self.ITextInstance {},
	社长对话8: class extends self.ITextInstance {},
	社长对话9: class extends self.ITextInstance {},
	_15a: class extends self.ITextInstance {},
	_15b: class extends self.ITextInstance {},
	_15c: class extends self.ITextInstance {},
	_15d: class extends self.ITextInstance {},
	旁白xl14: class extends self.ITextInstance {},
	社长名字3: class extends self.ITextInstance {},
	社长对话4: class extends self.ITextInstance {},
	旁白xl7: class extends self.ITextInstance {},
	万人迷姓名: class extends self.ITextInstance {},
	万人迷对话1: class extends self.ITextInstance {},
	主控内心os1: class extends self.ITextInstance {},
	旁白xl8: class extends self.ITextInstance {},
	_14a: class extends self.ITextInstance {},
	_14b: class extends self.ITextInstance {},
	_14c: class extends self.ITextInstance {},
	_14d: class extends self.ITextInstance {},
	社长对话3: class extends self.ITextInstance {},
	社长名字2: class extends self.ITextInstance {},
	同学1对话1: class extends self.ITextInstance {},
	_13a: class extends self.ITextInstance {},
	_13b: class extends self.ITextInstance {},
	_13c: class extends self.ITextInstance {},
	_13d: class extends self.ITextInstance {},
	旁白xl6: class extends self.ITextInstance {},
	_12a: class extends self.ITextInstance {},
	_12b: class extends self.ITextInstance {},
	_12c: class extends self.ITextInstance {},
	_12d: class extends self.ITextInstance {},
	旁白xl4: class extends self.ITextInstance {},
	旁白xl5: class extends self.ITextInstance {},
	社长名字: class extends self.ITextInstance {},
	社长对话1: class extends self.ITextInstance {},
	社长对话2: class extends self.ITextInstance {},
	旁白xl3: class extends self.ITextInstance {},
	_11a: class extends self.ITextInstance {},
	_11b: class extends self.ITextInstance {},
	_11c: class extends self.ITextInstance {},
	_11d: class extends self.ITextInstance {},
	心理活动室人逐渐变多: class extends self.IWorldInstance {},
	旁白xl2: class extends self.ITextInstance {},
	_10a: class extends self.ITextInstance {},
	_10b: class extends self.ITextInstance {},
	_10c: class extends self.ITextInstance {},
	_10d: class extends self.ITextInstance {},
	新人2: class extends self.ITextInstance {},
	新人: class extends self.ITextInstance {},
	旁白xl1: class extends self.ITextInstance {},
	旁白xl15: class extends self.ITextInstance {},
	旁白xl16: class extends self.ITextInstance {},
	旁白框底xl11: class extends self.ISpriteInstance {},
	旁白框xl11: class extends self.ISpriteInstance {},
	同学2图片: class extends self.ISpriteInstance {},
	社长姓名框8: class extends self.ISpriteInstance {},
	选项框底xl4: class extends self.ISpriteInstance {},
	旁白框底xl10: class extends self.ISpriteInstance {},
	旁白框xl10: class extends self.ISpriteInstance {},
	社长姓名框7: class extends self.ISpriteInstance {},
	_12a底: class extends self.ISpriteInstance {},
	_12b底: class extends self.ISpriteInstance {},
	_12c底: class extends self.ISpriteInstance {},
	_12d底: class extends self.ISpriteInstance {},
	旁白框底xl9: class extends self.ISpriteInstance {},
	同学1图片: class extends self.ISpriteInstance {},
	社长姓名框6: class extends self.ISpriteInstance {},
	旁白框底xl8: class extends self.ISpriteInstance {},
	旁白框xl8: class extends self.ISpriteInstance {},
	社长姓名框5: class extends self.ISpriteInstance {},
	旁白框底xl7: class extends self.ISpriteInstance {},
	旁白框xl7: class extends self.ISpriteInstance {},
	社长姓名框4: class extends self.ISpriteInstance {},
	社长: class extends self.ISpriteInstance {},
	旁白框底xl6: class extends self.ISpriteInstance {},
	旁白框xl6: class extends self.ISpriteInstance {},
	社长姓名框3: class extends self.ISpriteInstance {},
	旁白框底xl5: class extends self.ISpriteInstance {},
	旁白框xl5: class extends self.ISpriteInstance {},
	社长姓名框2: class extends self.ISpriteInstance {},
	旁白框底xl4: class extends self.ISpriteInstance {},
	旁白框xl4: class extends self.ISpriteInstance {},
	旁白框底xl3: class extends self.ISpriteInstance {},
	旁白框xl3: class extends self.ISpriteInstance {},
	社长姓名框: class extends self.ISpriteInstance {},
	选项框底xl3: class extends self.ISpriteInstance {},
	_11a底: class extends self.ISpriteInstance {},
	_11b底: class extends self.ISpriteInstance {},
	_11c底: class extends self.ISpriteInstance {},
	_11d底: class extends self.ISpriteInstance {},
	旁白框底xl2: class extends self.ISpriteInstance {},
	旁白框xl2: class extends self.ISpriteInstance {},
	选项框底xl2: class extends self.ISpriteInstance {},
	_10a底: class extends self.ISpriteInstance {},
	_10b底: class extends self.ISpriteInstance {},
	_10c底: class extends self.ISpriteInstance {},
	_10d底: class extends self.ISpriteInstance {},
	新人框2: class extends self.ISpriteInstance {},
	新人框: class extends self.ISpriteInstance {},
	旁白框底xl1: class extends self.ISpriteInstance {},
	旁白框xl1: class extends self.ISpriteInstance {},
	选项框底xl1: class extends self.ISpriteInstance {},
	_9a底: class extends self.ISpriteInstance {},
	_9b底: class extends self.ISpriteInstance {},
	_9c底: class extends self.ISpriteInstance {},
	_9d底: class extends self.ISpriteInstance {},
	小书被讨厌的勇气: class extends self.ISpriteInstance {},
	大书: class extends self.ISpriteInstance {},
	小海报1: class extends self.ISpriteInstance {},
	小海报2: class extends self.ISpriteInstance {},
	万人迷: class extends self.ISpriteInstance {},
	海报2: class extends self.ISpriteInstance {},
	心理活动室背景: class extends self.ISpriteInstance {},
	海报1: class extends self.ISpriteInstance {},
	人群: class extends self.ISpriteInstance {},
	乐手: class extends self.ISpriteInstance {},
	食堂门口: class extends self.ISpriteInstance {},
	食堂活动: class extends self.ITextInstance {},
	玩游戏吗: class extends self.ITextInstance {},
	游戏文字提示: class extends self.ITextInstance {},
	_19a: class extends self.ITextInstance {},
	_10a4: class extends self.ITextInstance {},
	_19b: class extends self.ITextInstance {},
	_19c: class extends self.ITextInstance {},
	_19d: class extends self.ITextInstance {},
	食堂精灵: class extends self.ISpriteInstance {},
	精灵13: class extends self.ISpriteInstance {},
	精灵14: class extends self.ISpriteInstance {},
	精灵15: class extends self.ISpriteInstance {},
	结果精灵: class extends self.ISpriteInstance {},
	报告消息: class extends self.ITextInstance {},
	结果消息: class extends self.ISpriteInstance {},
	最终数据: class extends self.ISpriteInstance {},
	查看结果: class extends self.ITextInstance {},
	精灵16: class extends self.ISpriteInstance {},
	结果评语2: class extends self.ITextInstance {},
	结果评语3: class extends self.ITextInstance {},
	结果评语4: class extends self.ITextInstance {},
	精灵17: class extends self.ISpriteInstance {},
	科普内容2: class extends self.ITextInstance {},
	建议1: class extends self.ITextInstance {},
	建议2: class extends self.ITextInstance {},
	建议3: class extends self.ITextInstance {},
	建议4: class extends self.ITextInstance {},
	小贴士: class extends self.ITextInstance {},
	结尾: class extends self.ISpriteInstance {},
	结束语1: class extends self.ITextInstance {},
	结束语2: class extends self.ITextInstance {},
	结束语3: class extends self.ITextInstance {},
	精灵18: class extends self.ISpriteInstance {},
	结束语4: class extends self.ITextInstance {},
	结束语5: class extends self.ITextInstance {},
	结束语6: class extends self.ITextInstance {},
	结束语7: class extends self.ITextInstance {},
	结束语8: class extends self.ITextInstance {},
	结束语9: class extends self.ITextInstance {},
	精灵19: class extends self.ISpriteInstance {},
	精灵20: class extends self.ISpriteInstance {},
	pic: class extends self.ISpriteInstance {},
	朋友d: class extends self.ISpriteInstance {},
	pic3: class extends self.ISpriteInstance {}
}